<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<title>FFTA</title>
		<link href="style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	</head>
	<nav>
		<div>
			<a href="index.html">ACCUEIL</a>
		</div>
		<div>
			<a href="CLASSEMENT.html" target="_blank">CLASSEMENTS</div>
			<div>
				<a href="INSCRIPTION.html" target="_blank">INSCRIPTION</div>
				<div>
					<a href="EVENEMENT.html" target="_blank">EVENEMENT</a>
				</div>
			</nav>
			<body>
				<header>
					<h1>Classements nationaux</h1>
				</header>
				<table>
					<caption>
						Top 10 Benjamin Femme 2021
					</caption>
					<thead>
						<tr>
							<th>
								Rang
							</th>
							<th>
								Archer
							</th>
							<th>
								Club
							</th>
							<th>
								S1
							</th>
							<th>
								S2
							</th>
							<th>
								S3
							</th>
							<th>
								Moy
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								1
							</td>
							<td>
								AMADUCCI MARIE DIANE
							</td>
							<td>
								ST JEAN LE BLANC
							</td>
							<td>
								915
							</td>
							<td>
								755
							</td>
							<td>
								720
							</td>
							<td>
								796
							</td>
						</tr>
						<tr>
							<td>
								2
							</td>
							<td>
								PHILIPPIN ABYGAELLE
							</td>
							<td>
								BONCOURT NVX ARCHERS
							</td>
							<td>
								750
							</td>
							<td>
								595
							</td>
							<td>
								540
							</td>
							<td>
								628
							</td>
						</tr>
						<tr>
							<td>
								3
							</td>
							<td>
								LECARDONNEL JADE
							</td>
							<td>
								PAVILLY
							</td>
							<td>
								660
							</td>
							<td>
								620
							</td>
							<td>
								575
							</td>
							<td>
								618
							</td>
						</tr>
						<tr>
							<td>
								4
							</td>
							<td>
								THION JULIE
							</td>
							<td>
								BELLEGARDE LA ROSE
							</td>
							<td>
								770
							</td>
							<td>
								615
							</td>
							<td>
								0
							</td>
							<td>
								461
							</td>
						</tr>
						<tr>
							<td>
								5
							</td>
							<td>
								DELGADO SARAH
							</td>
							<td>
								BLANQUEFORT
							</td>
							<td>
								775
							</td>
							<td>
								0
							</td>
							<td>
								0
							</td>
							<td>
								258
							</td>
						</tr>
						<tr>
							<td>
								6
							</td>
							<td>
								NDIENGO EMMY
							</td>
							<td>
								ROCHEFORT DU GARD
							</td>
							<td>
								670
							</td>
							<td>
								0
							</td>
							<td>
								0
							</td>
							<td>
								223
							</td>
						</tr>
						<tr>
							<td>
								7
							</td>
							<td>
								BERNARD AGATHE
							</td>
							<td>
								PERS EN GATINAIS
							</td>
							<td>
								665
							</td>
							<td>
								0
							</td>
							<td>
								0
							</td>
							<td>
								221
							</td>
						</tr>
						<tr>
							<td>
								8
							</td>
							<td>
								JALABERT LISE
							</td>
							<td>
								LEGUEVIN
							</td>
							<td>
								255 
							</td>
							<td>
								0
							</td>
							<td>
								0
							</td>
							<td>
								85
							</td>
						</tr>
						<tr>
							<td>
								9
							</td>
							<td>
								BASSO EGLANTINE
							</td>
							<td>
								MONTGISCARD
							</td>
							<td>
								200
							</td>
							<td>
								0
							</td>
							<td>
								0
							</td>
							<td>
								66
							</td>
						</tr>
						<tr>
							<td>
								10
							</td>
							<td>
								ERTZ DUGAST LOU
							</td>
							<td>
								NEUWILLER LES SAVERNE
							</td>
							<td>
								85
							</td>
							<td>
								0
							</td>
							<td>
								0
							</td>
							<td>
								28
							</td>
						</tr>
					</tbody>
				</table>
			</body>
		</html>
